language: python
dist: xenial
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37-codecov
    - python: 3.6
      stage: deploy
      env: TOXENV=docs
before_install:
  - pip install poetry tox tox-venv
  - |
    if [[ $TOXENV != docs ]]; then
      source .travis/install-mopac.sh
    fi
install: true
script: tox
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/build
  on:
    branch: master
    condition: $TOXENV = docs
